GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{ 
    "username": "Federico",
    "email": "fede@gmail.com",
    "password": "12345"
}

###
PUT http://localhost:3000/api/users/62cbde2cc54956526bba0402/product/62c7e61c468760159e8047b6
