GET http://localhost:3000/api/clientes

###
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Mario",
    "apellidos": "Girón",
    "direccion": "C Ballesta 26",
    "email": "mario1@gmail.com",
    "edad": 34,
    "genero": "m",
    "cuota": "19.90",
    "fecha_nacimiento": "1983-09-20",
    "dni": "8888888Y"
}

###
GET http://localhost:3000/api/profesores

###
POST http://localhost:3000/api/profesores
Content-Type: application/json

{
    "nombre": "Carmen Sevilla",
    "experiencia": 75
}

###
DELETE http://localhost:3000/api/clientes/101

###
GET http://localhost:3000/api/clientes/edad/74

###
PUT http://localhost:3000/api/clientes/94
Content-Type: application/json

{
    "nombre": "Flemming",
    "apellidos": "Churchley",
    "direccion": "129 Malasaña",
    "email": "fchurchley2l@forbes.com",
    "edad": 45,
    "genero": "m",
    "cuota": "19.90",
    "fecha_nacimiento": "2000-12-08",
    "dni": "010547249m" 
}

###
PUT http://localhost:3000/api/profesores/23
Content-Type: application/json

{
    "nombre": "Adrienne Johns",
    "experiencia": 13
}