GET http://localhost:3000/api/clientes

###
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nombre": "Mario",
    "apellidos": "Girón",
    "direccion": "C Ballesta 26",
    "email": "mario@gmail.com",
    "edad": 34,
    "genero": "m",
    "cuota": "19.90",
    "fecha_nacimiento": "1983-09-20",
    "dni": "8888888Y"
}

###
GET http://localhost:3000/api/profesores

###
POST http://localhost:3000/api/profesores
Content-Type: application/json

{
    "nombre": "Laura Montes",
    "experiencia": 4
}