GET http://localhost:3000/users

###
DELETE http://localhost:3000/personas/remove

###
GET http://localhost:3000/products/by-id

###
PUT http://localhost:3000/users/edit/form

### NUEVAS
GET http://localhost:3000/products/all

###
DELETE http://localhost:3000/users/borrar/all


###
POST http://localhost:3000/products/create/new
Content-Type: application/json

{
    "nombre": "lápiz rojo",
    "precio": 12,
    "departamento": "papelería"
}

###
PUT http://localhost:3000/edit

###
PUT http://localhost:3000/dashboard/personas/edit

###
GET http://localhost:3000/dashboard/personas

###
POST http://localhost:3000/dashboard/products/create

###
GET http://localhost:3000/dashboard/products/344423